require: rubocop-rails


AllCops:
  Exclude:
    - 'app/views/spree/api/**/*'
    - 'bin/*'
    - 'cache/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/support/fixture_builder.rb'
    - 'tmp/**/*'
    - 'db/data/*'
    - 'db/data_schema.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'lib/aws-sdk.rb'

Metrics/LineLength:
  Exclude:
    - 'config/initializers/content_security_policy.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/new_framework_defaults_6_0.rb'
    - 'config/environments/*.rb'
    - 'config/initializers/action_mailer.rb'
    - 'config/features.rb'
    - 'db/seeds.rb'
  Max: 100
